language: node_js
node_js:
  '10'
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
install:
  - npm install
script:
  - npm run clean
  - npm run build
  - npm test
